version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./tmp/localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  slatedb-node1:
    build: .
    environment:
      - NODE_ID=node-1
      - S3_ENDPOINT=http://localstack:4566
      - S3_BUCKET=slatedb-test
    depends_on:
      - localstack
    ports:
      - "8081:8080"

  slatedb-node2:
    build: .
    environment:
      - NODE_ID=node-2
      - S3_ENDPOINT=http://localstack:4566
      - S3_BUCKET=slatedb-test
    depends_on:
      - localstack
    ports:
      - "8082:8080"

  slatedb-node3:
    build: .
    environment:
      - NODE_ID=node-3
      - S3_ENDPOINT=http://localstack:4566
      - S3_BUCKET=slatedb-test
    depends_on:
      - localstack
    ports:
      - "8083:8080"